name: CI

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  IQM_BASE_URL: "https://resonance.meetiqm.com"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on:
          [
            ubuntu-24.04,
            ubuntu-24.04-arm,
            macos-26,
            macos-26-intel,
            windows-2025,
            windows-11-arm,
          ]
        iqm_qc_alias: ["emerald:mock", "garnet:mock"]

    steps:
      - name: Clone Repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install dependencies (Ubuntu)
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -y curl libcurl4-openssl-dev

      - name: Setup ccache
        if: ${{ !startsWith(matrix.runs-on, 'windows') }}
        uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639 # v1.2.20
        with:
          variant: ccache
          save: true
          max-size: 10G

      - name: Setup mold
        uses: rui314/setup-mold@725a8794d15fc7563f59595bd9556495c0564878 # v1

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_IQM_QDMI_TESTS=ON

      - name: Build
        run: cmake --build build --config Release -j4

      - name: Test
        working-directory: build
        env:
          IQM_QC_ALIAS: ${{ matrix.iqm_qc_alias }}
          RESONANCE_API_KEY: ${{ secrets.RESONANCE_API_KEY }}
          IQM_CPP_API_LOG_LEVEL: "DEBUG"
        run: ctest -C Release --verbose --output-on-failure --repeat until-pass:3 --timeout 180 --parallel 4

  test-install:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on:
          [
            ubuntu-24.04,
            ubuntu-24.04-arm,
            macos-26,
            macos-26-intel,
            windows-2025,
            windows-11-arm,
          ]
    steps:
      - name: Clone Repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install dependencies (Ubuntu)
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -y curl libcurl4-openssl-dev

      - name: Setup ccache
        if: ${{ !startsWith(matrix.runs-on, 'windows') }}
        uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639 # v1.2.20
        with:
          variant: ccache
          save: true
          max-size: 10G

      - name: Setup mold
        uses: rui314/setup-mold@725a8794d15fc7563f59595bd9556495c0564878 # v1

      - name: Configure CMake for installation
        run: cmake -S . -B build-install -DCMAKE_BUILD_TYPE=Release -DBUILD_IQM_QDMI_TESTS=OFF

      - name: Build the project
        run: cmake --build build-install --config Release --parallel 4

      - name: Install the project
        run: cmake --install build-install --prefix install-dir --config Release

      - name: Configure CMake for using installed version
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DUSE_INSTALLED_IQM_QDMI_DEVICE=ON -DCMAKE_PREFIX_PATH=install-dir

      - name: Build with installed version
        run: cmake --build build --config Release --parallel 4

      - name: Test installed version
        working-directory: build
        env:
          IQM_QC_ALIAS: "emerald:mock"
          RESONANCE_API_KEY: ${{ secrets.RESONANCE_API_KEY }}
          IQM_CPP_API_LOG_LEVEL: "DEBUG"
        run: ctest -C Release --output-on-failure --repeat until-pass:3 --timeout 180 --parallel 4
