name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl libcurl4-openssl-dev

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

      - name: Commit potential changes
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
        with:
          commit_message: ":hook: Apply pre-commit fixes"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

      - name: Generate compilation database
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Run clang-tidy
        id: linter
        uses: cpp-linter/cpp-linter-action@a645cdb1ded4f83d2a4af4b0e7929546bb040bea # v2.16.6
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          style: ""
          tidy-checks: ""
          database: "build"
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
          ignore: "build"
          version: "21"
          files-changed-only: true

      - if: steps.linter.outputs.checks-failed > 0
        run: exit 1
