name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl libcurl4-openssl-dev

      - name: Set up Clang
        env:
          TEMP_DIR: ${{ runner.temp }}
          CLANG_VERSION: 22
        run: |
          # Sanitize CLANG_VERSION: Remove any newlines and ensure it is numeric
          clang_version="$(echo "$CLANG_VERSION" | tr -d '\n')"
          if [[ -z "$clang_version" || ! "$clang_version" =~ ^[0-9]+$ ]]; then
            echo "Error: Invalid clang-version input. Must be a non-empty numeric value."
            exit 1
          fi
          wget https://apt.llvm.org/llvm.sh -O "$TEMP_DIR/llvm_install.sh"
          chmod +x "$TEMP_DIR/llvm_install.sh"
          if sudo "$TEMP_DIR/llvm_install.sh" "$clang_version"; then
            sudo apt-get install -y clang-"$clang_version" \
                                    clang-format-"$clang_version" \
                                    clang-tidy-"$clang_version" \
                                    clang-tools-"$clang_version" \
            || exit 1
          else
            echo "Installation from script failed."
            exit 1
          fi
          echo "CC=clang-$clang_version" >> $GITHUB_ENV
          echo "CXX=clang++-$clang_version" >> $GITHUB_ENV

      - name: Generate compilation database
        run: |
          echo $CC
          echo $CXX
          $CC --version
          $CXX --version
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Run clang-tidy
        id: linter
        uses: cpp-linter/cpp-linter-action@a645cdb1ded4f83d2a4af4b0e7929546bb040bea # v2.16.6
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          style: ""
          tidy-checks: ""
          database: "build"
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
          ignore: "build"
          version: "22"
          files-changed-only: true
          step-summary: true
          extra-args: "-std=c++20"

      - if: steps.linter.outputs.checks-failed > 0
        run: exit 1
