name: 🐍 • Packaging

on:
  workflow_call:
    inputs:
      runs-on:
        description: "The runner image to test on"
        default: "ubuntu-24.04"
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-python-packaging-cibw-${{ inputs.runs-on }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-wheel:
    name: 🎡 ${{ inputs.runs-on }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: ${{ !startsWith(inputs.runs-on, 'ubuntu') }}
          save-cache: ${{ github.ref == 'refs/heads/main' }}

      # run cibuildwheel to build wheels for the specified Python version
      - uses: pypa/cibuildwheel@8d2b08b68458a16aeb24b64e68a09ab1c8e82084 # v3.4.1

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      # upload the wheels as an artifact (adds a `dev-` prefix for PRs)
      - name: Upload wheels
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ github.event_name == 'pull_request' && 'dev-' || '' }}cibw-wheels-${{ inputs.runs-on }}
          path: wheelhouse/*.whl
