name: 🇸 • Tests • SPANK
on:
  workflow_call:
    inputs:
      runs-on:
        description: "The ubuntu runner image to use."
        default: "ubuntu-24.04"
        type: string
    secrets:
      IQM_TOKEN:
        required: false

permissions:
  contents: read

jobs:
  spank-tests:
    name: 🐧 ${{ inputs.runs-on }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build Docker image
        run: docker build -t qdmi-spank-tests -f spank/Dockerfile .

      - name: Run SPANK tests in Docker
        env:
          IQM_TOKEN: ${{ secrets.IQM_TOKEN }}
        run: |
          docker run --rm qdmi-spank-tests
